import { ApolloClient, InMemoryCache } from '@apollo/client'

/**
 * In order to retrieve data from fragments needs a list of "possibleTypes".
 * The "possibleTypes" are generated by Fragment Matcher plugin (see codegen.ts file).
 * 
 * More about Apollo and possible types:
 * https://www.apollographql.com/docs/react/data/fragments/#defining-possibletypes-manually
 * 
 * More abut Fragment Matcher plugin (GraphQL Code Generator):
 * https://the-guild.dev/graphql/codegen/plugins/other/fragment-matcher
 */
import generatedIntrospection from '../src/graphql/generated/introspection-result.json'

export const client = new ApolloClient({
  uri: process.env.UMBRACO_API_ENDPOINT,
  headers: {
    'Api-Key': String(process.env.UMBRACO_API_KEY),
    'Umb-Project-Alias': String(process.env.UMBRACO_PROJECT_ALIAS),
  },
  cache: new InMemoryCache({
    possibleTypes: generatedIntrospection.possibleTypes
  }),
})